---
title: "MC 4) Discussion"
author: "Nathan Brouwer | brouwern@gmail.com | @lobrowR"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = F,
  message = F
)
```



The final paper will include a brief (probably less than 1/2 page DS) discussion of the scientific implications & significance. 



```{r, echo = F, eval = F}
## Optional ##

# The following issues are not required to be addressed in 2018
# 
# If a study does not contain an experimental treatment, you should compare your study explicitly to the quantitative results of other similar studies & cite them appropriately.
# 
# For example, if you look at population trends for wood thrush in Pennsylvania, you should compare them to published information on trend in other places or over the entire country
# 
# As part of the discussion you should discuss how the experimental or study design might impact the results or conclusion, particularly how randomization was or was not used, if there is pseudoreplication, etc.

```

